export const QuestionsArray = [
    {
      id: 1,
      question: "Tell me about a product you launched successfully.",
      tags: ["Behavioral", "Product Design"]
    },
    {
      id: 2,
      question: "Estimate how many pizza delivery orders are made in a large city each day.",
      tags: ["Guesstimates", "Product Design"]
    },
    {
      id: 3,
      question: "What strategies would you use to increase user engagement on a mobile app?",
      tags: ["Product Strategy", "Product Design"]
    },
    {
      id: 4,
      question: "How would you analyze user data to improve a product's performance?",
      tags: ["Analytics", "Product Design"]
    },
    {
      id: 5,
      question: "Design a system for managing online payments securely.",
      tags: ["System Design", "Product Design"]
    },
    {
      id: 6,
      question: "Explain the technical architecture of a scalable web application.",
      tags: ["Technical", "Product Design"]
    },
    {
      id: 7,
      question: "Describe a situation where you had to make a difficult decision.",
      tags: ["Behavioral", "Leadership"]
    },
    {
      id: 8,
      question: "Estimate the number of cars passing through a toll booth in a day.",
      tags: ["Guesstimates", "Operations"]
    },
    {
      id: 9,
      question: "What would be your approach to entering a new market with a product?",
      tags: ["Market Entry Strategy", "Business Development"]
    },
    {
      id: 10,
      question: "How do you measure the success of a marketing campaign?",
      tags: ["Metrics", "Marketing"]
    },
    {
      id: 11,
      question: "Design a scalable infrastructure for a high-traffic e-commerce website.",
      tags: ["System Design", "Technical"]
    },
    {
      id: 12,
      question: "Explain a complex technical concept to a non-technical audience.",
      tags: ["Communication", "Technical"]
    },
    {
      id: 13,
      question: "Describe a time when you had to prioritize tasks under tight deadlines.",
      tags: ["Behavioral", "Time Management"]
    },
    {
      id: 14,
      question: "Estimate the revenue generated by a popular mobile app.",
      tags: ["Guesstimates", "Financial Analysis"]
    },
    {
      id: 15,
      question: "What strategies would you use to retain customers in a competitive market?",
      tags: ["Customer Retention", "Product Strategy"]
    },
    {
      id: 16,
      question: "How do you interpret A/B test results to make data-driven decisions?",
      tags: ["Analytics", "Data Analysis"]
    },
    {
      id: 17,
      question: "Design a fault-tolerant system for a real-time messaging application.",
      tags: ["System Design", "Technical"]
    },
    {
      id: 18,
      question: "Explain the difference between machine learning and deep learning.",
      tags: ["Technical", "Machine Learning"]
    },
    {
      id: 19,
      question: "Describe a challenging project you successfully completed.",
      tags: ["Behavioral", "Project Management"]
    },
    {
      id: 20,
      question: "Estimate the market size for electric cars in the next five years.",
      tags: ["Guesstimates", "Market Research"]
    },
    {
      id: 21,
      question: "What product features would you prioritize based on user feedback?",
      tags: ["Product Management", "User Feedback"]
    },
    {
      id: 22,
      question: "How do you analyze customer behavior to optimize a website's performance?",
      tags: ["Analytics", "User Experience"]
    },
    {
      id: 23,
      question: "Design a scalable microservices architecture for a cloud-based application.",
      tags: ["System Design", "Cloud Computing"]
    },
    {
      id: 24,
      question: "Explain the process of continuous integration and continuous deployment.",
      tags: ["Technical", "DevOps"]
    },
    {
      id: 25,
      question: "Describe a time when you had to resolve a conflict within a team.",
      tags: ["Behavioral", "Conflict Resolution"]
    },
    {
      id: 26,
      question: "Estimate the market share of a leading smartphone brand in a specific region.",
      tags: ["Guesstimates", "Market Analysis"]
    },
    {
      id: 27,
      question: "What pricing strategy would you recommend for a new software product?",
      tags: ["Product Strategy", "Pricing"]
    },
    {
      id: 28,
      question: "How do you analyze customer feedback to improve product usability?",
      tags: ["Analytics", "Usability Testing"]
    },
    {
      id: 29,
      question: "Design an authentication system for a secure online banking platform.",
      tags: ["System Design", "Security"]
    },
    {
      id: 30,
      question: "Explain the concept of virtualization and its benefits in cloud computing.",
      tags: ["Technical", "Virtualization"]
    },
    {
      id: 31,
      question: "Describe a situation where you had to adapt to unexpected changes.",
      tags: ["Behavioral", "Adaptability"]
    },
    {
      id: 32,
      question: "Estimate the number of daily active users on a popular social media platform.",
      tags: ["Guesstimates", "Social Media"]
    },
    {
      id: 33,
      question: "How would you launch a new feature in an existing product?",
      tags: ["Product Management", "Feature Launch"]
    },
    {
      id: 34,
      question: "What metrics would you track to assess the success of a content marketing campaign?",
      tags: ["Analytics", "Content Marketing"]
    },
    {
      id: 35,
      question: "Design a distributed system for real-time data processing.",
      tags: ["System Design", "Big Data"]
    },
    {
      id: 36,
      question: "Explain the concept of version control and its importance in software development.",
      tags: ["Technical", "Version Control"]
    },
    {
      id: 37,
      question: "Describe a time when you had to lead a team through a challenging project.",
      tags: ["Behavioral", "Leadership"]
    },
    {
      id: 38,
      question: "Estimate the revenue potential of a new subscription-based service.",
      tags: ["Guesstimates", "Revenue Forecasting"]
    },
    {
      id: 39,
      question: "What distribution channels would you use to reach a global audience?",
      tags: ["Market Entry Strategy", "Global Marketing"]
    },
    {
      id: 40,
      question: "How do you measure customer satisfaction and loyalty?",
      tags: ["Metrics", "Customer Experience"]
    },
   
    {
        id: 41,
        question: "Design a recommendation engine for an e-commerce platform.",
        tags: ["System Design", "Recommendation Systems"]
      },
      {
        id: 42,
        question: "Explain the difference between waterfall and agile software development methodologies.",
        tags: ["Technical", "Software Development"]
      },
      {
        id: 43,
        question: "Describe a time when you had to handle a difficult customer or client.",
        tags: ["Behavioral", "Customer Service"]
      },
      {
        id: 44,
        question: "Estimate the market demand for electric scooters in urban areas.",
        tags: ["Guesstimates", "Market Analysis"]
      },
      {
        id: 45,
        question: "What features would you prioritize in a mobile app for productivity?",
        tags: ["Product Management", "Mobile App"]
      },
      {
        id: 46,
        question: "How do you use data visualization to communicate insights effectively?",
        tags: ["Analytics", "Data Visualization"]
      },
      {
        id: 47,
        question: "Design a high-availability architecture for a real-time chat application.",
        tags: ["System Design", "High Availability"]
      },
      {
        id: 48,
        question: "Explain the concept of continuous monitoring in cybersecurity.",
        tags: ["Technical", "Cybersecurity"]
      },
      {
        id: 49,
        question: "Describe a time when you had to handle a project with limited resources.",
        tags: ["Behavioral", "Resource Management"]
      },
      {
        id: 50,
        question: "Estimate the potential impact of implementing AI in a manufacturing process.",
        tags: ["Guesstimates", "Artificial Intelligence"]
      }
    ];
    