export const QuestionsArray = [
    {
      id: 1,
      question: "Tell me about a product you launched successfully.",
    tags: ['Product Design', "Behavioral"]
    },
    {
      id: 2,
      question: "Estimate how many pizza delivery orders are made in a large city each day.",
    tags: ['Product Design', "Product Strategy"]
    },
    {
      id: 3,
      question: "What strategies would you use to increase user engagement on a mobile app?",
    tags: ['Product Design', "System Design"]
    },
    {
      id: 4,
      question: "How would you analyze user data to improve a product's performance?",
    tags: ['Product Design', "Analytics"]
    },
    {
      id: 5,
      question: "Design a system for managing online payments securely.",
    tags: ['Product Design', "System Design"]
    },
    {
      id: 6,
      question: "Explain the technical architecture of a scalable web application.",
    tags: ['Product Design', "Behavioral"]
    },
    {
      id: 7,
      question: "Describe a situation where you had to make a difficult decision.",
    tags: ['Product Design', "Technical"]
    },
    {
      id: 8,
      question: "Estimate the number of cars passing through a toll booth in a day.",
    tags: ['Product Design', "Product Strategy"]
    },
    {
      id: 9,
      question: "What would be your approach to entering a new market with a product?",
    tags: ['Product Design', "System Design"]
    },
    {
      id: 10,
      question: "How do you measure the success of a marketing campaign?",
    tags: ['Product Design', "Behavioral"]
    },
      
      {
      id: 11,
      question: "Design a scalable infrastructure for a high-traffic e-commerce website.",
      tags: ['Product Design', "Analytics"]
    },
      
      {
      id: 12,
      question: "Explain a complex technical concept to a non-technical audience.",
      tags: ['Product Design', "Analytics"]
    },
      
      {
      id: 13,
      question: "Describe a time when you had to prioritize tasks under tight deadlines.",
      tags: ['Product Design', "Behavioral"]
    },
      
      {
      id: 14,
      question: "Estimate the revenue generated by a popular mobile app.",
      tags: ['Product Design', "System Design"]
    },
      
      {
      id: 15,
      question: "What strategies would you use to retain customers in a competitive market?",
      tags: ['Product Design', "Technical"]
    },
      
      {
      id: 16,
      question: "How do you interpret A/B test results to make data-driven decisions?",
      tags: ['Product Design', "Guesstimates"]
    },
      
      {
      id: 17,
      question: "Design a fault-tolerant system for a real-time messaging application.",
      tags: ['Product Design', "Behavioral"]
    },
      
      {
      id: 18,
      question: "Explain the difference between machine learning and deep learning.",
      tags: ['Product Design', "Analytics"]
    },
      
      {
      id: 19,
      question: "Describe a challenging project you successfully completed.",
      tags: ['Product Design', "System Design"]
    },
      
      {
      id: 20,
      question: "Estimate the market size for electric cars in the next five years.",
      tags: ['Product Design', "Product Strategy"]
    },
    {
      id: 21,
      question: "What product features would you prioritize based on user feedback?",
    tags: ['Product Design', "Behavioral"]
    },
    {
      id: 22,
      question: "How do you analyze customer behavior to optimize a website's performance?",
    tags: ['Product Design', "Guesstimates"]
    },
    {
      id: 23,
      question: "Design a scalable microservices architecture for a cloud-based application.",
    tags: ['Product Design', "Technical"]
    },
    {
      id: 24,
      question: "Explain the process of continuous integration and continuous deployment.",
    tags: ['Product Design', "Technical"]
    },
    {
      id: 25,
      question: "Describe a time when you had to resolve a conflict within a team.",
    tags: ['Product Design', "Behavioral"]
    },
    {
      id: 26,
      question: "Estimate the market share of a leading smartphone brand in a specific region.",
    tags: ['Product Design', "Technical"]
    },
    {
      id: 27,
      question: "What pricing strategy would you recommend for a new software product?",
    tags: ['Product Design', "Guesstimates"]
    },
    {
      id: 28,
      question: "How do you analyze customer feedback to improve product usability?",
    tags: ['Product Design', "Product Strategy"]
    },
    {
      id: 29,
      question: "Design an authentication system for a secure online banking platform.",
    tags: ['Product Design', "Analytics"]
    },
    {
      id: 30,
      question: "Explain the concept of virtualization and its benefits in cloud computing.",
    tags: ['Product Design', "Behavioral"]
    },
    {
      id: 31,
      question: "Describe a situation where you had to adapt to unexpected changes.",
    tags: ['Product Design', "Guesstimates"]
    },
    {
      id: 32,
      question: "Estimate the number of daily active users on a popular social media platform.",
    tags: ['Product Design', "Analytics"]
    },
    {
      id: 33,
      question: "How would you launch a new feature in an existing product?",
    tags: ['Product Design', "Product Strategy"]
    },
    {
      id: 34,
      question: "What metrics would you track to assess the success of a content marketing campaign?",
    tags: ['Product Design', "Guesstimates"]
    },
    {
      id: 35,
      question: "Design a distributed system for real-time data processing.",
    tags: ['Product Design', "System Design"]
    },
    {
      id: 36,
      question: "Explain the concept of version control and its importance in software development.",
    tags: ['Product Design', "Behavioral"]
    },
    {
      id: 37,
      question: "Describe a time when you had to lead a team through a challenging project.",
    tags: ['Product Design', "Guesstimates"]
    },
    {
      id: 38,
      question: "Estimate the revenue potential of a new subscription-based service.",
    tags: ['Product Design', "Analytics"]
    },
    {
      id: 39,
      question: "What distribution channels would you use to reach a global audience?",
    tags: ['Product Design', "Behavioral"]
    },
    {
      id: 40,
      question: "How do you measure customer satisfaction and loyalty?",
    tags: ['Product Design', "Guesstimates"]
    },
   
    {
        id: 41,
        question: "Design a recommendation engine for an e-commerce platform.",
    tags: ['Product Design', "Product Strategy"]
      },
      {
        id: 42,
        question: "Explain the difference between waterfall and agile software development methodologies.",
      tags: ['Product Design', "Analytics"]
      },
      {
        id: 43,
        question: "Describe a time when you had to handle a difficult customer or client.",
      tags: ['Product Design', "Technical"]
      },
      {
        id: 44,
        question: "Estimate the market demand for electric scooters in urban areas.",
      tags: ['Product Design', "System Design"]
      },
      {
        id: 45,
        question: "What features would you prioritize in a mobile app for productivity?",
      tags: ['Product Design', "Guesstimates"]
      },
      {
        id: 46,
        question: "How do you use data visualization to communicate insights effectively?",
      tags: ['Product Design', "Analytics"]
      },
      {
        id: 47,
        question: "Design a high-availability architecture for a real-time chat application.",
      tags: ['Product Design', "Product Strategy"]
      },
      {
        id: 48,
        question: "Explain the concept of continuous monitoring in cybersecurity.",
      tags: ['Product Design', "Guesstimates"]
      },
      {
        id: 49,
        question: "Describe a time when you had to handle a project with limited resources.",
      tags: ['Product Design', "Behavioral"]
      },
      {
        id: 50,
        question: "Estimate the potential impact of implementing AI in a manufacturing process.",
      tags: ['Product Design', "Technical"]
      },
      
  {
    id: 51,
    question: "Explain the concept of blockchain technology and its applications.",
  tags: ['Product Design', "Guesstimates"]
  },
  {
    id: 52,
    question: "Describe a time when you had to handle a crisis or emergency situation.",
  tags: ['Product Design', "Analytics"]
  },
  {
    id: 53,
    question: "Estimate the market size for artificial intelligence solutions in healthcare.",
  tags: ['Product Design', "System Design"]
  },
  {
    id: 54,
    question: "What are your strategies for managing a remote team effectively?",
  tags: ['Product Design', "Behavioral"]
  },
  {
    id: 55,
    question: "How would you approach optimizing a website for search engine ranking?",
  tags: ['Product Design', "Analytics"]
  },
  {
    id: 56,
    question: "Design a disaster recovery plan for a cloud-based infrastructure.",
  tags: ['Product Design', "Technical"]
  },
  {
    id: 57,
    question: "Explain the concept of machine learning algorithms and their types.",
  tags: ['Product Design', "Product Strategy"]
  },
  {
    id: 58,
    question: "Describe a situation where you had to negotiate a beneficial deal.",
  tags: ['Product Design', "Behavioral"]
  },
  {
    id: 59,
    question: "Estimate the market demand for electric bicycles in urban areas.",
  tags: ['Product Design', "Technical"]
  },
  {
    id: 60,
    question: "What strategies would you use to enhance user privacy in a digital product?",
  tags: ['Product Design', "Guesstimates"]
  },
  {
    id: 61,
    question: "How do you analyze customer churn and implement retention strategies?",
  tags: ['Product Design', "Analytics"]
  },
  {
    id: 62,
    question: "Design an efficient data storage solution for a large-scale application.",
  tags: ['Product Design', "Behavioral"]
  },
  {
    id: 63,
    question: "Explain the concept of cybersecurity threats and preventive measures.",
  tags: ['Product Design', "Product Strategy"]
  },
  {
    id: 64,
    question: "Describe a time when you had to handle a difficult stakeholder.",
  tags: ['Product Design', "Analytics"]
  },
  {
    id: 65,
    question: "Estimate the market share of a new entrant in the gaming industry.",
  tags: ['Product Design', "System Design"]
  },
  {
    id: 66,
    question: "What steps would you take to improve employee engagement in a company?",
  tags: ['Product Design', "Behavioral"]
  },
  {
    id: 67,
    question: "How do you analyze customer feedback to enhance product features?",
  tags: ['Product Design', "Guesstimates"]
  },
  {
    id: 68,
    question: "Design a scalable infrastructure for real-time data analytics.",
  tags: ['Product Design', "Technical"]
  },
  {
    id: 69,
    question: "Explain the concept of cloud-native applications and their benefits.",
  tags: ['Product Design', "Analytics"]
  },
  {
    id: 70,
    question: "Describe a time when you had to manage a project with conflicting priorities.",
  tags: ['Product Design', "Product Strategy"]
  },
  {
    id: 71,
    question: "Estimate the market potential for renewable energy solutions in a specific region.",
  tags: ['Product Design', "Behavioral"]
  },
  {
    id: 72,
    question: "What strategies would you implement to improve customer support services?",
  tags: ['Product Design', "System Design"]
  },
  {
    id: 73,
    question: "How do you conduct user testing to validate product design decisions?",
  tags: ['Product Design', "Analytics"]
  },
  {
    id: 74,
    question: "Design a scalable architecture for real-time video streaming.",
  tags: ['Product Design', "Guesstimates"]
  },
  {
    id: 75,
    question: "Explain the concept of microservices and their advantages in software development.",
  tags: ['Product Design', "Product Strategy"]
  },
  {
    id: 76,
    question: "Describe a time when you had to resolve a customer complaint effectively.",
  tags: ['Product Design', "Behavioral"]
  },
  {
    id: 77,
    question: "Estimate the market share of a leading e-commerce platform in the next year.",
  tags: ['Product Design', "Technical"]
  },
  {
    id: 78,
    question: "What strategies would you use to build brand awareness for a new product?",
  tags: ['Product Design', "Analytics"]
  },
  {
    id: 79,
    question: "How do you analyze website performance metrics to optimize user experience?",
  tags: ['Product Design', "Technical"]
  },
  {
    id: 80,
    question: "Design a secure communication protocol for IoT devices.",
  tags: ['Product Design', "Guesstimates"]
  },
  {
    id: 81,
    question: "Explain the concept of continuous improvement and its role in organizational growth.",
  tags: ['Product Design', "Product Strategy"]
  },
  {
    id: 82,
    question: "Describe a time when you had to lead a team through a major change initiative.",
  tags: ['Product Design', "Behavioral"]
  },
  {
    id: 83,
    question: "Estimate the market size for virtual reality applications in education.",
  tags: ['Product Design', "System Design"]
  },
  {
    id: 84,
    question: "What strategies would you use to reduce customer acquisition costs?",
  tags: ['Product Design', "Analytics"]
  },
  {
    id: 85,
    question: "How do you analyze user behavior data to improve product personalization?",
  tags: ['Product Design', "Technical"]
  },
  {
    id: 86,
    question: "Design a scalable database architecture for a global e-commerce platform.",
  tags: ['Product Design', "Guesstimates"]
  },
  {
    id: 87,
    question: "Explain the concept of edge computing and its applications in IoT.",
  tags: ['Product Design', "Product Strategy"]
  },
  {
    id: 88,
    question: "Describe a time when you had to deal with a difficult vendor or supplier.",
  tags: ['Product Design', "Behavioral"]
  },
  {
    id: 89,
    question: "Estimate the market demand for subscription-based streaming services.",
  tags: ['Product Design', "Analytics"]
  },
  {
    id: 90,
    question: "What strategies would you use to improve employee retention rates?",
  tags: ['Product Design', "System Design"]
  },
  {
    id: 91,
    question: "How do you analyze customer feedback to enhance service quality in hospitality?",
  tags: ['Product Design', "Behavioral"]
  },
  {
    id: 92,
    question: "Design an automated testing framework for a web application.",
  tags: ['Product Design', "Guesstimates"]
  },
  {
    id: 93,
    question: "Explain the concept of supply chain management and its key components.",
  tags: ['Product Design', "Analytics"]
  },
  {
    id: 94,
    question: "Describe a time when you had to resolve a technical issue under pressure.",
  tags: ['Product Design', "Product Strategy"]
  },
  {
    id: 95,
    question: "Estimate the market potential for AI-powered chatbots in customer service.",
  tags: ['Product Design', "Behavioral"]
  },
  {
    id: 96,
    question: "What strategies would you use to improve software development productivity?",
  tags: ['Product Design', "Analytics"]
  },
  {
    id: 97,
    question: "How do you analyze market trends to identify new business opportunities?",
  tags: ['Product Design', "Technical"]
  },
  {
    id: 98,
    question: "Design a scalable backend architecture for a social media platform.",
  tags: ['Product Design', "Guesstimates"]
  },
  {
    id: 99,
    question: "Explain the concept of machine vision and its applications in robotics.",
  tags: ['Product Design', "Behavioral"]
  },
  {
    id: 100,
    question: "Describe a time when you had to handle a customer's escalated complaint.",
  tags: ['Product Design', "Product Strategy"]
  },
    ];
    